### ISSUE TITLE
lag is smaller than 0

### ISSUE THREAD

**Issue by yuankui** [yahoo/kafka-manager#216]
hi, my kafka-manager
version is : `kafka-manager-1.3.0.4`

![image](https://cloud.githubusercontent.com/assets/236535/14041647/f7df8e1c-f2ad-11e5-8873-2e1e8e9d2329.png)

**Comment by patelh** [comment]
Yes, that can happen, if you are using the kafka consumer, we are reading the topic for offsets which is going to be processed much faster then the producer topic offset polling.

**Comment by yuankui** [comment]
we also setup a https://github.com/quantifind/KafkaOffsetMonitor, how could it show the lag correctly?(at least not smaller than 0)

**Comment by patelh** [comment]
I'm not certain how KafkaOffsetMonitor gets the producer offsets.  It's possible they do it on the fly.  Kafka Manager on the other hand allows you to configure the polling period since it is not scalable to attempt to get all the lag for every topic when we render the list of topics page with hundreds of topics.  If you don't have a lot of topics, you can reduce the polling period in the cluster config.

**Comment by yuankui** [comment]
@patelh then how to "configure the polling period since", thx!

**Comment by patelh** [comment]
Use 1.3.0.7 and change the polling period in the cluster config view.

**Comment by wangycc** [comment]
How to configure the polling period of 1.3.3.22 version? 
![image](https://user-images.githubusercontent.com/12569878/55541971-add7f400-56f8-11e9-8d34-bbfd128f82cf.png)
