### ISSUE TITLE
Is it possible to add cluster through config?

### ISSUE THREAD

**Issue by functicons** [yahoo/kafka-manager#635]
Seems the only way to add a cluster is from the UI, wondering is it possible to add cluster through config (before starting the Kafka Manager server)?

**Comment by jthompson6** [comment]
You need to set your zookeeper hosts with the 
`kafka-manager.zkhosts` parameter in the configuration file.

You can then point to the file with 
`-Dconfig.file` as in https://github.com/yahoo/kafka-manager#starting-the-service

**Comment by functicons** [comment]
Thanks @jthompson6, but that is not for adding cluster. IIUC, KM itself uses ZK (specified via kafka-manager.zkhosts) as data store to manage cluster configs, but after that, you have to add cluster through the UI. I guess it might be possible to directly write config to the ZK, but there is no doc for that, and that is internal implementation detail, which might change over time.

**Comment by montana-ua** [comment]
Since KM can manage more than one kafka cluster, its store a configuration (related to kafka cluster) in ZK DB (kafka manager config is not the best place for it). If you want to add a kafka cluster to your kafka manager w/o UI, use API (e.g. you can deploy a kafka manager via ansible and after that add a cluster via API by ansible).

**Comment by svergun** [comment]
@jomendoz, why you don't want to try to find this information by yourself? It's very easy. I'm just a Kafka manager user, not a developer or contributor.
API routes are here - https://github.com/yahoo/kafka-manager/blob/master/conf/routes
